my_blog/article/urls.py
"""
article route path
"""

from django.urls import path

from . import views

app_name = 'article'

"""save the url paths"""
urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
]

my_blog/comment/urls.py
from django.urls import path

from . import views

app_name = 'article'

"""save the url paths"""
urlpatterns = [
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment')
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('', views.article_list, name='home'),
    path('admin/', admin.site.urls),

    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password_reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/article/models.py
"""
create model
"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

"""processing time-related transactions"""
from django.utils import timezone

# Create your models here.

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # use cascade method to delete data
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)  # save the time when post was created
    updated = models.DateTimeField(auto_now=True)  # save the time when post was updated
    total_view = models.PositiveIntegerField(default=0)

    """standardize the behavior of data"""
    class Meta:
        """
        ordering: Specify the order of the data returned by model
        -created: Reverse Order
        """
        ordering = ('-created', )

    def __str__(self):
        """return value when __str__ was called"""
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

my_blog/article/forms.py
"""
forms
"""

from django import forms

from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost  # data model source
        fields = ('title', 'body')  # fields contained in the form

my_blog/article/views.py
"""
@hichens
"""


from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.db.models import Q
from django.core.paginator import Paginator
import markdown

from .models import ArticlePost
from .forms import ArticlePostForm
from comment.models import Comment

# Create your views here.

"""show the articles"""
def article_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')

    if search:
        if request.GET.get('order') == 'total_view':
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_view')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        search = ''
        if order == 'total_view':
            article_list = ArticlePost.objects.all().order_by('-total_view')
        else:
            article_list = ArticlePost.objects.all()

    paginator = Paginator(article_list, 2)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {'articles': articles, 'order': order, 'search': search}
    return render(request, 'article/list.html', context)


"""show the article detail"""
def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)

    article.total_view += 1
    article.save(update_fields=['total_view'])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    context = {'article': article, 'toc': md.toc, 'comments': comments}

    return render(request, 'article/detail.html', context)

"""write article"""
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            return redirect('article:article_list')
        else:
            return HttpResponse("表单错误, 请重新填写")

    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)


"""delete article safely"""
def article_safe_delete(request, id):
    if request.method == "POST":
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect('article:article_list')
    else:
        return HttpResponse('仅允许post请求')


"""update article"""
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)

    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章")

    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        new_article = request.POST
        if article_post_form.is_valid():
            article.title = new_article['title']
            article.body = new_article['body']
            article.save()
            return redirect('article:article_detail', id=id)
        else:
            return HttpResponse("表单错误, 请重新填写")

    else:
        article_post_form = ArticlePostForm()
        context = {
            'article': article,
            'article_post_form': article_post_form,
        }
        return render(request, 'article/update.html', context)

my_blog/templates/article/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} 写文章 {% endblock title%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>

            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>

                <div class="form-group">
                    <label for="body">正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">完成</button>

            </form>

        </div>
    </div>
</div>

{% endblock content %}

my_blog/templates/article/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title%}title{% endblock title%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert-success">
                 <div>
                    作者：{{ article.author }}
                    {% if user == article.author %}
                        · <a href="#" onclick="confirm_delete()">删除文章</a>
                        · <a href="{% url "article:article_update" article.id %}">
                            编辑文章
                        </a>
                    {% endif %}
                </div>
                <div>
                    浏览：{{ article.total_view }}
                </div>
                <!-- hidden form -->
                <form style="display: none" id="safe_delete"
                      action="{% url 'article:article_safe_delete' article.id %} " method="post">
                    {% csrf_token %}
                    <button type="submit">发送</button>
                </form>

            </div>

            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>

                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form
                            action="{% url 'comment:post_comment' article.id %}"
                            method="POST"
                        >
                        {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言：
                                    </strong>
                                </label>
                                <textarea
                                    type="text"
                                    class="form-control"
                                    id="body"
                                    name="body"
                                    rows="2"></textarea>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}

                <h4>共有{{ comments.count }}条评论</h4>
                <div>
                    {% for comment in comments %}
                        <hr>
                        <p>
                            <strong style="color: pink">
                                {{ comment.user }}
                            </strong> 于
                            <span style="color: green">
                                {{ comment.created|date:"Y-m-d H:i:s" }}
                            </span> 时说：
                        </p>
                        <pre style="font-family: inherit; font-size: 1em;">
                            {{ comment.body }}</pre>
                    {% endfor %}
                </div>
        </div>

         <!-- 目录 -->
         <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
    </div>
</div>

<script>
function confirm_safe_delete() {
    layer.open({
        title: "确认删除",
        content: "确认删除这篇文章吗?",
        yes: function(index, layero){
            $('form#safe_delete button').click();
            layer.close()
        },
    })
}
</script>

{% endblock content %}

my_blog/templates/article/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    首页
{% endblock %}

{% block content %}
<!-- 定义放置文章标题的div容器 -->
<div class="container">

    <nav aria-label="breadcrumd">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}">最新</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_view&search={{ search }}">最热</a>
            </li>
        </ol>
    </nav>

     <!-- 搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required
                >
            </form>
        </div>
    </div>

    <!-- 搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}

    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                    <span>
                        <small class="col align-self-end" style="color: gray;">
                            浏览: {{ article.total_view }}
                        </small>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo; 首页
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                       class="btn btn-success"
                    >
                        尾页 &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock content %}

my_blog/templates/article/update.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} 写文章 {% endblock title%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <div class="form-group">
                    <label for="body">正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}